services:
  - name: my-app
    type: compose
    plan: hobby
    env:
      - key: FRONTEND_URL
        value: https://api.render.com/deploy/srv-cfqgu2qrrk08lt7gptk0?key=kpQ_U5r-Ckk
      - key: DB_URL
        value: jdbc:mysql://api.render:3306/notes
      - key: DB_USERNAME
        value: user
      - key: DB_PASSWORD
        value: password
    repo: alejoGalizzi/repo
    docker_compose_path: docker-compose.yml
    docker_compose_config: |
      version: '3'
      services:
        frontend:
          image: alejoGalizzi/frontend
          ports:
            - 80:3000
        backend:
          image: alejoGalizzi/backend
          ports:
            - 8080:8080
        db:
          image: mysql:8.0
          environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: notes
          volumes:
            - db-data:/var/lib/mysql

      volumes:
        db-data:
